### PR TITLE
EIR PlantLoop Heat Pump Test Files

### PR DESCRIPTION
**Pull request by mitchute**
Adding EIR PLHP test files. These were added at E+ [#7489](https://github.com/NREL/EnergyPlus/pull/7489).

### CODE REVIEW

**Comment by Myoldmopar** [comment]
I really need to get rid of this manual file listing...

**Comment by mitchute** [comment]
@Myoldmopar see my most recent commit as a case for your recommendation...

**Comment by Myoldmopar** [comment]
:rofl:

**Comment by Myoldmopar** [comment]
It's almost like I need to do something about this manual file list...

**Pull request merged**
