### PR TITLE
Enable Reverse Design Day Simulations

### PR DESCRIPTION
**Pull request by mitchute**

### CODE REVIEW

**Comment by Myoldmopar** [comment]
After #57 merges, we should pull `master` into this branch, move the GUI changes to the new file, and fix that one flake8 issue if it is still present.  It would be great to be able to run reverse DD runs easily again.

**Comment by Myoldmopar** [comment]
We definitely need to look back into this.  And maybe even more urgently, we need to do a "Run/ResetState/ReRun" configuration as well.

**Comment by mitchute** [comment]
A separate but related issue would be to compare results across platforms as well.

**Comment by Myoldmopar** [comment]
OK, reverse DD is now integrated in E+ CTest itself, the regression tool doesn't need to do anything here.  And if anything needs to be done for cross platform diffs, it would be at a much higher level, not in this regression tool code.  Closing this.  Thanks @mitchute !

**Pull request closed without merging**
